[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

; Partición estándar para apps grandes sin BT
board_build.partitions = huge_app.csv

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=0
    -D MATRIX_GREEN=0x07E0

lib_deps =
    lovyan03/LovyanGFX @ ^1.2.19
    mikalhart/TinyGPSPlus @ ^1.1.0
    crankyoldgit/IRremoteESP8266 @ ^2.9.0
    nrf24/RF24 @ ^1.5.0
    WiFi
    SD
    SPI
    FS
    adafruit/Adafruit NeoPixel @ ^1.12.0